### ISSUE TITLE
Medigoron crash

### ISSUE THREAD

**Issue by AndyNPC** [Roman971/OoT-Randomizer#15]
Looks like talking to Medigoron will crash the game on console if he's shuffled and you have Biggoron Sword. I haven't tested it without Biggoron Sword, so I'm not sure if that's actually related. I haven't tried it on emulator either.  Anyways, here's the spoiler log and nice little PNG with a yellow bar in the corner. 
[OoT_C1B7C_WhackySnacky_Spoiler.txt](https://github.com/Roman971/OoT-Randomizer/files/4316255/OoT_C1B7C_WhackySnacky_Spoiler.txt)
![oot_rando_crash](https://user-images.githubusercontent.com/37420234/76386189-36640900-633a-11ea-8d25-6bfa62c66c6f.PNG)

**Comment by Roman971** [comment]
Thanks for the report.
As far I know this only happens on N64 and a specific emulator core. It's high on my priority list but I haven't had time to look into it yet.

**Comment by Roman971** [comment]
This crash should now be fixed as of version 5.2.12 R-4.
