### ISSUE TITLE
Crashing after 1000 Horseback Archery

### ISSUE THREAD

**Issue by UofCWildcat** [Roman971/OoT-Randomizer#17]
Have had this now happen twice since using the Dev Build on Everdrive with N64 Hardware (compressed file). Once I complete the first 1000 pt Archery challenge at Gerudo Fortress my game crashes right before acquiring the item.

**Comment by Roman971** [comment]
Thank you for the report. This crash should be fixed as of version 5.2.12 R-3.
Please let me know if it still happens.

**Comment by UofCWildcat** [comment]
Just ran a Plandomizer with what I needed for the Archery check. Ran over and attempted the run and got through! Thanks again for the assistance!

(NOTE: this was on 5.2.12 R-4)
