### ISSUE TITLE
Custom music crackling sound

### ISSUE THREAD

**Issue by Flax4** [Roman971/OoT-Randomizer#22]
Custom music doesn't work properly, a lot of crackling sounds going on. On testrunners builds (master and dev) it works just fine. However BizHawk must be involved somehow due to custom music with your builds work just fine when playing through the new Modloader from the OoT Online team.

**Comment by Roman971** [comment]
Thanks for the report. I'm looking into it.

**Comment by Roman971** [comment]
This issue should be fixed as of version 5.2.13 R-3 (cb312765c543417e7033bfa9c496e75eda76d6d5).
Whenever you play again, let me know if it's still a problem or not on your end.

**Comment by Flax4** [comment]
It seems to be fixed, thank you!
