### ISSUE TITLE
Visual Bug (Seizure Warning)

### ISSUE THREAD

**Issue by darkangel93x** [Roman971/OoT-Randomizer#29]
https://discordapp.com/channels/274180765816848384/438698093354156032/743127407153643681

TrenterToday at 17:23
@Roman You there? Somewhat serious issue. Mixed Entrances + Decoupled. Ice Cavern -> Desert Collossus (From HW) created a Huge Seizure-like Flickering.

**Comment by fenhl** [comment]
This sounds like the same issue that was fixed in TestRunnerSRL#1299, so it can probably be closed.

**Comment by Roman971** [comment]
Closing since this should be fixed as mentioned above.
