### ISSUE TITLE
[feature-request] Replace the Zora Sapphire model by its randomized replacement in Jabu

### ISSUE THREAD

**Issue by Et0san** [Roman971/OoT-Randomizer#4]
# Explanation
Assume beating Barinade gives the Forest Medallion. The objective is to replace the freestanding Zora Sapphire before the miniboss in Jabu Jabu's belly (and the Zora Sapphire model hold up by Ruto soon after) by a model of the Forest Medallion.

# Why?
Assume you have not seen the altar yet (for example, you got rang+RL in child 1 domain WOTH and went straight to Jabu cause you don't have Farore to do it later). You do the entire Jabu until the miniboss, and see a:
Case 1 - Freestanding Stone: You leave Jabu now, saving some time.
Case 2 - Freestanding Med: You finish the dungeon.

# No, seriously, why?
Because it's fancy.

# Problems
Might be hard to attack the hardcoded existing "Taa daa daa daa" models of the Meds. Might be easier for the stones that are already floating over the altar.
Might be hard to attack the Zora Sapphire model in Ruto's cinematic sequence.

**Comment by Roman971** [comment]
This is a thing now, the Zora Sapphire model is accurate based on the dungeon reward, so I'll be closing this.
Note that it was also merged in TR's fork a while ago.
