### ISSUE TITLE
Crashing in Stingers inside Jabu Jabu

### ISSUE THREAD

**Issue by jdeng89** [Roman971/OoT-Randomizer#41]
In two seeds my Everdrive 2.5 has frozen killing Stingers in Jabu Jabu.

Currently I'm on Dev-R-test-settings.

Emu players I've raced with have not reported crashing.

`  ":version":                  "5.2.65 R-9 Test-1",
  "file_hash":                 ["Big Magic", "Beans", "Hover Boots", "Lens of Truth", "Stone of Agony"],
  ":seed":                     "LJBH1TSEW5",
  ":settings_string":          "AJTWFFCSKJA9WAAACAASAEPRPTACSJWJAKALERCAEACABNAEWBTSELTPER5M9CJBUSAJGBABASR2WBE",`

Highlighted VOD: https://www.twitch.tv/videos/775004810

**Comment by r0bd0g** [comment]
https://i.imgur.com/36awCXM.png
https://i.imgur.com/I1casFE.png
https://i.imgur.com/kj3pNS9.png
https://i.imgur.com/JfihN4q.png
https://i.imgur.com/MKgrZAF.png
https://i.imgur.com/OU6rSMf.png
https://i.imgur.com/urnq6SF.png

Fig Today at 8:07 PM
crashing instruction is trunc.w.s f18, f16. whatever is in f16 is apparently not a float.
function is func_8008FA80 on 1.0, SkinMatrix_MtxFToMtx in decomp if anyone wants to dig further
