### ISSUE TITLE
Seed crashing when exiting Windmill

### ISSUE THREAD

**Issue by rchrm5** [Roman971/OoT-Randomizer#45]
This seed crashes each time the Windmill is exited as child (entered from playing Requiem of Spirit). I assume this has to do with the sandstorm actor that's supposed to load when entering Gerudo Fortress from Wasteland, as that was a problem in the past with Beta Quest, but not for certain.

[OoT_43A0A_3O9Y1ZA6WA_Spoiler.zip](https://github.com/Roman971/OoT-Randomizer/files/5514143/OoT_43A0A_3O9Y1ZA6WA_Spoiler.zip)

Edit: Here are the error message screens from the Debugger in order:

Screen 1: "HungUp on Thread 4
                 RCP is HUNG UP!!"

Screen 2: "actor dlftbls 471
                 No.             RamStart-RamEnd               Offset
                   9               80240870-802416a0           006270b0
                  24              801dd530-801e1ef0            006a85d0
                  35              802416d0-802426a0           00654030
                  291            801e5df0-801e65a0            00897960
                  339            801e4da0-801e5af0            008dda10
                  465            801e2760-801e33a0           0099d100"

Screen 3:  "CallBack (1) 800088a8 00000000 00000000"

**Comment by Roman971** [comment]
This should no longer be an issue since standstorm transitions were fixed in https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1299, so I'm closing it for now
